name: Docs

on:
  push:
    branches: [main, develop]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - run: sftp ${{secrets.web_user}}@${{secrets.web_ip}} | ${{secrets.web_pass}} | yes
      - run: put -r docs/. public_html/
      - run: exit