name: Publish Docs
on:
  push:
    branches: [main, develop]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docs
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.web_ip }}
          ftp-username: ${{ secrets.web_user }}
          ftp-password: ${{ secrets.web_pass }}
          local-dir: docs/*